### ISSUE TITLE
Image picker packages not working after installation of this package

### ISSUE THREAD

**Issue by vishwanath-awate** [nitish24p/react-native-upi#16]
i installed this package along with react-native-image-crop-picker & react-native-image-picker.

App crashes after I select image from image picker dialog. If I uninstall upi package then image picker works fine.

**Comment by jitendra-koodo** [comment]
we also face similar problem, but on phone # selection [pop-up](https://4.bp.blogspot.com/-H3wBrYcICPI/WeEjPy6tPsI/AAAAAAAAEqc/db1ff-kSnkEYCfaaiTbA2qeXnSPoOtnNwCLcBGAs/s1600/image3.png). Not sure if something with the dialog/selector...

No error message was printed on console.

**Comment by sarath263** [comment]
Handled this by just adding a condition. See  #21

**Comment by nitish24p** [comment]
@sarath263 Thanks

**Comment by Aneeshpissay** [comment]
Image Picker package is not working
