### ISSUE TITLE
Error: You have exceeded the maximum transaction amount set by your bank

### ISSUE THREAD

**Issue by realabbas** [nitish24p/react-native-upi#22]
Error: "You have exceeded the maximum transaction amount set by your bank"

Paying through Google Pay shows "You have exceeded the maximum transaction amount set by your bank". It was working perfectly fine but now this error has occurred.

**Comment by nitish24p** [comment]
I dont think this is a module issue.. This is from your issuing bank..

**Comment by realabbas** [comment]
> I dont think this is a module issue.. This is from your issuing bank..

It's working fine if I use the Google Pay app directly. It's just throwing error when used in-app.

**Comment by esafwan** [comment]
From my understanding, Intent flow is now only supported to merchant ids. If you try to pay to a merchant it will work fine. This error message is thrown when you are trying to pay to normal upi id. 

See:
[](https://stackoverflow.com/questions/62953449/getting-error-you-have-exceeded-the-maximum-transaction-amount-set-by-your-bank)
[](https://github.com/PatilShreyas/EasyUpiPayment-Android/issues/67)
[](https://www.blueappsoftware.com/google-pay-error-bank-limit-exceeded/)

**Comment by desraj173** [comment]
It is working fine if you use merchant account of Google pay for receiving payments

**Comment by realabbas** [comment]
> Error: "You have exceeded the maximum transaction amount set by your bank"
> 
> Paying through Google Pay shows "You have exceeded the maximum transaction amount set by your bank". It was working perfectly fine but now this error has occurred.

Yes in order to resolve the issue, the receiver UPI should be merchant.

**Comment by KaleRucha** [comment]
I am using merchant account only still I am getting this error. Please help

**Comment by kaushaldarji29** [comment]
ya after adding the merchant upi id and when i try to do payment  i got this error from payment app " this transection may be risky. for your safety, it can't be completed at this time" .. please provide the solution..

**Comment by aaryan359** [comment]
Is there any solution for this or not?
