### ISSUE TITLE
Issue with google pay app

### ISSUE THREAD

**Issue by ramprakashreddy** [nitish24p/react-native-upi#25]
![image](https://user-images.githubusercontent.com/36103674/111074354-91f64300-8508-11eb-8346-3a842651f261.jpeg)

Issue with google pay app, if i cancel the payment after opening the gpay app , the application is crashing, it is working with other UPI apps, When i had checked using logs, i found that while using Gpay app , Failure callback funtion returns data which does not contain "data.nameValuePairs.message;". so it is giving an error since it is undefined.

Gpay App returns data as 
![image](https://user-images.githubusercontent.com/36103674/111074494-38dadf00-8509-11eb-9b39-4ed898adf3da.png)
other apps return data which contains message as well 
![image](https://user-images.githubusercontent.com/36103674/111074529-5ad46180-8509-11eb-9033-9b7899e1431a.png)
I have tried fixing it by adding a small condition in UPIPayment.js file.

Can anyone confirm if they are facing the same issue , if so i could submit a PR to fix this

**Comment by nitish24p** [comment]
Yea you can give a PR for this.. seems like a hygiene fix

**Comment by ramprakashreddy** [comment]
> Yea you can give a PR for this.. seems like a hygiene fix

@nitish24p  please check i have created a PR #26

**Comment by ramprakashreddy** [comment]
@nitish24p any update on the issue , please check PR #26

**Comment by ramprakashreddy** [comment]
Fixed with PR #26
