### ISSUE TITLE
project with path ':react-native-api-payment' could not found in root project

### ISSUE THREAD

**Issue by cullsin** [nitish24p/react-native-upi#3]
Hi, 

I am getting the below error message, 
"project with path ':react-native-api-payment' could not found in root project" 

There are two build.gradle file. I just did the latest react-native-cli. 

One of the build.grade dependency says that, 

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

Please suggest me.

![image](https://user-images.githubusercontent.com/5137598/56909119-39a92a00-6ac5-11e9-9336-87a201007db9.png)

**Comment by cullsin** [comment]
Resloved. Sorry I did not check properly

**Comment by nitish24p** [comment]
```
include ':react-native-upi-payment'
project(':react-native-upi-payment').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-upi-payment/android')
```

It should be `react-native-upi-payment` not `react-native-upi`

**Comment by goldenaman** [comment]
I ejected a expo app and tried following the steps here https://www.npmjs.com/package/react-native-upi-payment

getting error  A problem occurred evaluating project ':react-native-upi-payment'. 
Could not find method compile() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
