### ISSUE TITLE
Error when installing and configuring project

### ISSUE THREAD

**Issue by Rohan-Rajesh** [nitish24p/react-native-upi#33]
Hi,

I wanted to implement UPI payment in my application and I found this package and it was exactly what I needed... But after following all the installation steps, when I run the app it fails.

Here is a screenshot of the entire error I get:
![Screenshot 2021-08-06 at 8 18 15 PM](https://user-images.githubusercontent.com/79851447/128529231-9fb75692-bfa2-4df0-ac26-ee661feb03d4.png)

If anyone could help in solving this error, It would be much appreciated

Thanks

**Comment by nitish24p** [comment]
@Rohan-Rajesh What was the solve for this
