### ISSUE TITLE
who is sender and recipient ?

### ISSUE THREAD

**Issue by cullsin** [nitish24p/react-native-upi#4]
Hi, 

It works awesome. Can you please suggest me how do I transfer the amount between two users? sender and receiver? 

Can you please suggest me.

Raja K

**Comment by nitish24p** [comment]
So user 1 has to know the upi id of user 2
Assume user 1 ===SEND MONEY TO===> User 2

```javascript

RNUpiPayment.initializePayment({
  vpa: 'john@upi', // user 2 upi handle
  payeeName: 'John Doe', // name of user 2
  amount: '1', // amount to transfer
  transactionRef: 'aasf-332-aoei-fn' // some transaction id that you will identify with your Backend
}, successCallback, failureCallback);
```

**Comment by cullsin** [comment]
Hello, 
Sorry. I did not understand. In which account money will deduct and which account it receive.

**Comment by cullsin** [comment]
Do I need any prerrquest about the sender?

**Comment by nitish24p** [comment]
Money will get deducted from user 1 and go to user 2

**Comment by cullsin** [comment]
Thanks. Can you give example of sender as well as receiver UPI. In the RN initalize, the UPi key is sender or receiver?

**Comment by cullsin** [comment]
I can see only one UPi. Where is the other one?
