### ISSUE TITLE
i am facing this issue during build please help me it is very urgent

### ISSUE THREAD

**Issue by ritikmatta** [nitish24p/react-native-upi#47]
Could not find method compile() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by ritikmatta** [comment]
can anyone help me to implement this i stuck there from many days but did not find any solution.i would appreciate your help.

**Comment by nitish24p** [comment]
can you try this
```
dependencies {
    compile 'com.facebook.react:react-native:+' // OLD
}
dependencies {
    implementation 'com.facebook.react:react-native:+' // Replace To
}

```

**Comment by ritikmatta** [comment]
I tried but able to make a build

**Comment by ritikmatta** [comment]
please help me

**Comment by ritikmatta** [comment]
can you connect with me  @nitish24p on 9215767100 and i have sent you request on linkedin from id ritik matta please help me

**Comment by nitish24p** [comment]
Please do not put any of your personal information as a comment here 😄

**Comment by nitish24p** [comment]
Did you try the change, if it didnt work can you send me some code of the build.gradle file so i can help

**Comment by itsmesubham** [comment]
@ritikmatta  Replace compile with implementation in node_modules> react-native-upi > android > build.gradle

**Comment by getsettalk** [comment]
just  put this into  **_android/app/build.gradle_**
`
dependencies {
    implementation 'com.facebook.react:react-native:'
}
`

it's works for me

**Comment by nitish24p** [comment]
Update to the latest version this should get fixed..
