### ISSUE TITLE
You have exceeded limit.

### ISSUE THREAD

**Issue by sayakbiswas13** [nitish24p/react-native-upi#53]
I am getting this error of , You have exceeded daily limit of the bank. Please fix this issue if you know what it is. I need to use this package.

**Comment by sayakbiswas13** [comment]
@nitish24p please help me with this.

**Comment by nitish24p** [comment]
@sayakbiswas13
Can you put a breakpoint here https://github.com/nitish24p/react-native-upi/blob/master/android/src/main/java/com/upi/payment/UpiPaymentModule.java#L78 and post the payload here..

Closing since its a duplicate of 
https://github.com/nitish24p/react-native-upi/issues/46
